-- MANUAL MIGRATION SCRIPT FOR FEATURED SERVICES
-- Run this script in your PostgreSQL interface (pgAdmin, phpPgAdmin, etc.)

-- 1. Enable UUID extension if not available (Standard for UUID generation)
-- SAFE MIGRATION SCRIPT (Using new table name to avoid ownership conflicts)

-- 1. ALTER EXISTING TABLE (Add is_staff_pick to services)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'services' AND column_name = 'is_staff_pick') THEN
        ALTER TABLE services ADD COLUMN is_staff_pick BOOLEAN DEFAULT FALSE;
    END IF;
END $$;

-- 2. CREATE TABLE (New name: featured_promotions)
CREATE TABLE IF NOT EXISTS featured_promotions (
    id UUID PRIMARY KEY, -- ID generated by application (Node.js)
    service_id UUID NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    payment_status VARCHAR(20) CHECK (payment_status IN ('PAID', 'PENDING_DEDUCTION', 'EXPIRED', 'PENDING')),
    target_keywords JSONB DEFAULT '[]'::jsonb,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. INDEXES
CREATE INDEX IF NOT EXISTS idx_featured_promotions_service_id ON featured_promotions(service_id);
CREATE INDEX IF NOT EXISTS idx_featured_promotions_status ON featured_promotions(payment_status);
CREATE INDEX IF NOT EXISTS idx_featured_promotions_keywords ON featured_promotions USING GIN (target_keywords);

-- 4. TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION update_featured_promotions_modtime()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 5. TRIGGER
DROP TRIGGER IF EXISTS trg_update_featured_promotions_modtime ON featured_promotions;

CREATE TRIGGER trg_update_featured_promotions_modtime
    BEFORE UPDATE ON featured_promotions
    FOR EACH ROW
    EXECUTE FUNCTION update_featured_promotions_modtime();
