import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import { pool } from '../config/db.js';
import logger from '../config/logger.js';
import AlertService, { SEVERITY } from '../services/alertService.js';
import { sendEmail } from '../services/notificationService.js';

// JWT_SECRET MUST be set in cPanel environment variables
const JWT_SECRET = process.env.JWT_SECRET;
if (!JWT_SECRET) {
    throw new Error('FATAL: JWT_SECRET environment variable is not set.');
}
const JWT_EXPIRES_IN = '24h';
const SALT_ROUNDS = 10;
const RESET_CODE_EXPIRY_MINUTES = 15;
const RESET_SESSION_EXPIRY = '10m';

// REGISTER CONTROLLER
export const register = async (req, res, next) => {
    try {
        const { email, password, role, fullName, phone } = req.body;

        // 1. Check if user already exists
        const userCheck = await pool.query('SELECT id FROM users WHERE email = $1', [email]);
        if (userCheck.rows.length > 0) {
            return res.status(409).json({ status: 'error', message: 'User already exists' });
        }

        // 2. Hash Password
        const passwordHash = await bcrypt.hash(password, SALT_ROUNDS);

        // 3. Insert User (UUID is generated by DB default gen_random_uuid())
        // 3. Insert User (UUID is generated by DB default gen_random_uuid())
        const newUser = await pool.query(
            'INSERT INTO users (email, password_hash, role, full_name) VALUES ($1, $2, $3, $4) RETURNING id, email, role, full_name, created_at',
            [email, passwordHash, role, fullName]
        );

        const user = newUser.rows[0];

        // 4. Create Provider Profile Placeholder if role is provider
        if (role === 'provider') {
            const tempRut = `TEMP-${Date.now()}`; // Temporary RUT until KYC
            const providerName = fullName || `Provider ${user.email}`;
            // CODE-SIDE FIX: Insert placeholders for non-nullable columns to bypass DB migration issues
            await pool.query(
                `INSERT INTO provider_profiles 
                (user_id, full_name, rut, phone, is_verified, bio, coverage_area, coverage_communes) 
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb)`,
                [
                    user.id,
                    providerName,
                    tempRut,
                    phone || null,
                    false,
                    'Pendiente de configurar', // Placeholder for bio (NOT NULL)
                    'Pendiente',               // Placeholder for coverage_area (NOT NULL)
                    JSON.stringify([])
                ]
            );
        }

        // 5. Generate Token
        const token = jwt.sign(
            { id: user.id, role: user.role, email: user.email },
            JWT_SECRET,
            { expiresIn: JWT_EXPIRES_IN }
        );

        // 6. Response (Stateless - Token in body)
        res.status(201).json({
            status: 'success',
            message: 'User registered successfully',
            token,
            user: {
                id: user.id,
                email: user.email,
                role: user.role,
            },
        });

    } catch (err) {
        logger.error(`Register Error: ${err.message}`);
        await AlertService.notify(err, { component: 'Auth', action: 'Register', email: req.body.email }, SEVERITY.HIGH);
        next(err);
    }
};

// LOGIN CONTROLLER
export const login = async (req, res, next) => {
    try {
        const { email, password } = req.body;

        // 1. Find User
        const result = await pool.query('SELECT * FROM users WHERE email = $1', [email]);

        if (result.rows.length === 0) {
            return res.status(401).json({ status: 'error', message: 'Invalid credentials' });
        }

        const user = result.rows[0];

        if (user.is_blocked) {
            return res.status(403).json({ status: 'error', message: 'Cuenta bloqueada. Contacta a soporte.' });
        }

        // 2. Compare Password
        const isMatch = await bcrypt.compare(password, user.password_hash);
        if (!isMatch) {
            return res.status(401).json({ status: 'error', message: 'Invalid credentials' });
        }

        // 3. Generate Token
        const token = jwt.sign(
            { id: user.id, role: user.role, email: user.email },
            JWT_SECRET,
            { expiresIn: JWT_EXPIRES_IN }
        );

        // 3.5 Fetch Profile Info (if provider)
        let profileData = {};
        if (user.role === 'provider') {
            const profileRes = await pool.query('SELECT full_name, profile_image_url FROM provider_profiles WHERE user_id = $1', [user.id]);
            if (profileRes.rows.length > 0) {
                profileData = profileRes.rows[0];
            }
        }

        // 4. Response
        res.json({
            status: 'success',
            message: 'Login successful',
            token,
            user: {
                id: user.id,
                email: user.email,
                role: user.role,
                full_name: profileData.full_name || user.email,
                profile_image_url: profileData.profile_image_url
            },
        });

    } catch (err) {
        logger.error(`Login Error: ${err.message}`);
        next(err);
    }
};


// =====================================================
// PASSWORD RECOVERY FLOW
// =====================================================

/**
 * Generate HTML email template for password reset code.
 * Made rich and detailed to avoid spam classification.
 */
const buildResetCodeEmailHTML = (code, userEmail) => {
    const platformName = 'Serviciosatuhogar';
    const year = new Date().getFullYear();
    const expiryMinutes = RESET_CODE_EXPIRY_MINUTES;
    
    return `
    <!DOCTYPE html>
    <html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Recuperación de Contraseña - ${platformName}</title>
    </head>
    <body style="margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f7fa; color: #333;">
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background-color: #f4f7fa;">
            <tr>
                <td align="center" style="padding: 40px 20px;">
                    <table role="presentation" width="600" cellspacing="0" cellpadding="0" border="0" style="background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.08); overflow: hidden;">
                        
                        <!-- Header -->
                        <tr>
                            <td style="background: linear-gradient(135deg, #f97316 0%, #ea580c 100%); padding: 32px 40px; text-align: center;">
                                <h1 style="margin: 0; color: #ffffff; font-size: 24px; font-weight: 700; letter-spacing: -0.5px;">${platformName}</h1>
                                <p style="margin: 8px 0 0; color: rgba(255,255,255,0.9); font-size: 14px;">Plataforma de Servicios para el Hogar</p>
                            </td>
                        </tr>

                        <!-- Icon -->
                        <tr>
                            <td align="center" style="padding: 40px 40px 20px;">
                                <div style="width: 72px; height: 72px; background-color: #fff7ed; border-radius: 50%; display: inline-flex; align-items: center; justify-content: center; border: 2px solid #fed7aa;">
                                    <span style="font-size: 32px;">🔐</span>
                                </div>
                            </td>
                        </tr>

                        <!-- Title -->
                        <tr>
                            <td style="padding: 0 40px 16px; text-align: center;">
                                <h2 style="margin: 0; color: #1f2937; font-size: 22px; font-weight: 700;">Solicitud de Recuperación de Contraseña</h2>
                            </td>
                        </tr>

                        <!-- Description -->
                        <tr>
                            <td style="padding: 0 40px 24px; text-align: center;">
                                <p style="margin: 0; color: #6b7280; font-size: 15px; line-height: 1.6;">
                                    Hemos recibido una solicitud para restablecer la contraseña asociada a la cuenta 
                                    <strong style="color: #374151;">${userEmail}</strong>. 
                                    Para continuar con el proceso de recuperación, utiliza el siguiente código de verificación:
                                </p>
                            </td>
                        </tr>

                        <!-- Code Box -->
                        <tr>
                            <td align="center" style="padding: 0 40px 24px;">
                                <div style="background-color: #f9fafb; border: 2px dashed #d1d5db; border-radius: 12px; padding: 24px 32px; display: inline-block;">
                                    <p style="margin: 0 0 8px; color: #6b7280; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; font-weight: 600;">Tu código de verificación</p>
                                    <p style="margin: 0; font-size: 36px; font-weight: 800; color: #f97316; letter-spacing: 8px; font-family: 'Courier New', monospace;">${code}</p>
                                </div>
                            </td>
                        </tr>

                        <!-- Expiry Warning -->
                        <tr>
                            <td align="center" style="padding: 0 40px 32px;">
                                <p style="margin: 0; color: #ef4444; font-size: 13px; font-weight: 600;">
                                    ⏳ Este código expira en ${expiryMinutes} minutos
                                </p>
                            </td>
                        </tr>

                        <!-- Steps -->
                        <tr>
                            <td style="padding: 0 40px 32px;">
                                <div style="background-color: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 10px; padding: 24px;">
                                    <h3 style="margin: 0 0 16px; color: #166534; font-size: 15px; font-weight: 700;">📋 Pasos a seguir:</h3>
                                    <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td style="padding: 6px 0; vertical-align: top;">
                                                <span style="display: inline-block; width: 24px; height: 24px; background-color: #16a34a; color: white; border-radius: 50%; text-align: center; line-height: 24px; font-size: 12px; font-weight: 700;">1</span>
                                            </td>
                                            <td style="padding: 6px 0 6px 12px; color: #374151; font-size: 14px; line-height: 1.5;">
                                                Regresa a la página de <strong>recuperación de contraseña</strong> en ${platformName}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="padding: 6px 0; vertical-align: top;">
                                                <span style="display: inline-block; width: 24px; height: 24px; background-color: #16a34a; color: white; border-radius: 50%; text-align: center; line-height: 24px; font-size: 12px; font-weight: 700;">2</span>
                                            </td>
                                            <td style="padding: 6px 0 6px 12px; color: #374151; font-size: 14px; line-height: 1.5;">
                                                Haz clic en <strong>"Ingresar código"</strong> e ingresa el código de 6 dígitos que aparece arriba
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="padding: 6px 0; vertical-align: top;">
                                                <span style="display: inline-block; width: 24px; height: 24px; background-color: #16a34a; color: white; border-radius: 50%; text-align: center; line-height: 24px; font-size: 12px; font-weight: 700;">3</span>
                                            </td>
                                            <td style="padding: 6px 0 6px 12px; color: #374151; font-size: 14px; line-height: 1.5;">
                                                Crea tu <strong>nueva contraseña</strong> (mínimo 8 caracteres, con mayúscula, minúscula y número)
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="padding: 6px 0; vertical-align: top;">
                                                <span style="display: inline-block; width: 24px; height: 24px; background-color: #16a34a; color: white; border-radius: 50%; text-align: center; line-height: 24px; font-size: 12px; font-weight: 700;">4</span>
                                            </td>
                                            <td style="padding: 6px 0 6px 12px; color: #374151; font-size: 14px; line-height: 1.5;">
                                                ¡Listo! Inicia sesión con tu nueva contraseña
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </td>
                        </tr>

                        <!-- Security Notice -->
                        <tr>
                            <td style="padding: 0 40px 32px;">
                                <div style="background-color: #fef3c7; border: 1px solid #fde68a; border-radius: 10px; padding: 20px;">
                                    <p style="margin: 0; color: #92400e; font-size: 13px; line-height: 1.6;">
                                        <strong>🔒 Nota de seguridad:</strong> Si tú no solicitaste este código, puedes ignorar este correo de forma segura. 
                                        Tu contraseña actual seguirá funcionando con normalidad. Nadie puede acceder a tu cuenta sin este código.
                                    </p>
                                </div>
                            </td>
                        </tr>

                        <!-- Footer -->
                        <tr>
                            <td style="background-color: #f9fafb; border-top: 1px solid #e5e7eb; padding: 24px 40px; text-align: center;">
                                <p style="margin: 0 0 8px; color: #9ca3af; font-size: 12px;">
                                    Este es un mensaje automático enviado por ${platformName}.
                                </p>
                                <p style="margin: 0 0 8px; color: #9ca3af; font-size: 12px;">
                                    Si tienes problemas, contáctanos en <a href="mailto:soporte@serviciosatuhogar.cl" style="color: #f97316; text-decoration: none;">soporte@serviciosatuhogar.cl</a>
                                </p>
                                <p style="margin: 0; color: #d1d5db; font-size: 11px;">
                                    © ${year} ${platformName}. Todos los derechos reservados.
                                </p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </body>
    </html>
    `;
};

// POST /api/auth/forgot-password
// Generates a 6-digit code, hashes it, stores in DB, sends via email
export const requestPasswordReset = async (req, res, next) => {
    try {
        const { email } = req.body;

        // Always return success to prevent user enumeration
        const genericMessage = 'Si el correo está registrado en nuestra plataforma, recibirás un código de verificación en los próximos minutos.';

        // 1. Find user
        const result = await pool.query('SELECT id, email FROM users WHERE email = $1', [email.toLowerCase()]);
        
        if (result.rows.length === 0) {
            // Return same message to prevent enumeration
            logger.info(`[Password Reset] Requested for non-existent email: ${email}`);
            return res.json({ status: 'success', message: genericMessage });
        }

        const user = result.rows[0];

        // 2. Generate 6-digit code
        const code = crypto.randomInt(100000, 999999).toString();
        
        // 3. Hash the code before storing (security best practice)
        const hashedCode = await bcrypt.hash(code, SALT_ROUNDS);
        
        // 4. Store hashed code + expiry in DB
        const expires = new Date(Date.now() + RESET_CODE_EXPIRY_MINUTES * 60 * 1000);
        await pool.query(
            'UPDATE users SET reset_token = $1, reset_token_expires = $2, updated_at = NOW() WHERE id = $3',
            [hashedCode, expires, user.id]
        );

        // 5. Send email with rich template
        const emailHTML = buildResetCodeEmailHTML(code, user.email);
        const emailSent = await sendEmail({
            to: user.email,
            subject: `🔐 Código de verificación: ${code} — Recuperación de contraseña | Serviciosatuhogar`,
            html: emailHTML
        });

        if (!emailSent) {
            logger.error(`[Password Reset] Failed to send email to: ${user.email}`);
        } else {
            logger.info(`[Password Reset] Code sent to: ${user.email}`);
        }

        res.json({ status: 'success', message: genericMessage });

    } catch (err) {
        logger.error(`Password Reset Request Error: ${err.message}`);
        await AlertService.notify(err, { component: 'Auth', action: 'RequestPasswordReset' }, SEVERITY.MEDIUM);
        next(err);
    }
};

// POST /api/auth/verify-reset-code
// Validates the 6-digit code and returns a short-lived JWT for the reset step
export const verifyResetCode = async (req, res, next) => {
    try {
        const { email, code } = req.body;

        // 1. Find user with valid reset token
        const result = await pool.query(
            'SELECT id, reset_token, reset_token_expires FROM users WHERE email = $1',
            [email.toLowerCase()]
        );

        if (result.rows.length === 0) {
            return res.status(400).json({ 
                status: 'error', 
                message: 'Código inválido o expirado. Por favor, solicita un nuevo código.' 
            });
        }

        const user = result.rows[0];

        // 2. Check if token exists and hasn't expired
        if (!user.reset_token || !user.reset_token_expires) {
            return res.status(400).json({ 
                status: 'error', 
                message: 'No hay una solicitud de recuperación activa. Por favor, solicita un nuevo código.' 
            });
        }

        if (new Date() > new Date(user.reset_token_expires)) {
            // Clean up expired token
            await pool.query('UPDATE users SET reset_token = NULL, reset_token_expires = NULL WHERE id = $1', [user.id]);
            return res.status(400).json({ 
                status: 'error', 
                message: 'El código ha expirado. Por favor, solicita uno nuevo.' 
            });
        }

        // 3. Compare code with hashed version
        const isMatch = await bcrypt.compare(code, user.reset_token);
        if (!isMatch) {
            return res.status(400).json({ 
                status: 'error', 
                message: 'Código incorrecto. Verifica el código e intenta nuevamente.' 
            });
        }

        // 4. Code is valid! Generate a short-lived reset session token
        const resetSessionToken = jwt.sign(
            { id: user.id, purpose: 'password_reset' },
            JWT_SECRET,
            { expiresIn: RESET_SESSION_EXPIRY }
        );

        // 5. Clear the used code from DB
        await pool.query('UPDATE users SET reset_token = NULL, reset_token_expires = NULL WHERE id = $1', [user.id]);

        logger.info(`[Password Reset] Code verified for user: ${user.id}`);

        res.json({
            status: 'success',
            message: 'Código verificado correctamente. Ahora puedes crear tu nueva contraseña.',
            resetToken: resetSessionToken
        });

    } catch (err) {
        logger.error(`Verify Reset Code Error: ${err.message}`);
        next(err);
    }
};

// POST /api/auth/reset-password
// Consumes the reset session token and sets a new password
export const resetPassword = async (req, res, next) => {
    try {
        const { resetToken, newPassword } = req.body;

        // 1. Verify the reset session token
        let decoded;
        try {
            decoded = jwt.verify(resetToken, JWT_SECRET);
        } catch (jwtErr) {
            return res.status(400).json({ 
                status: 'error', 
                message: 'La sesión de recuperación ha expirado. Por favor, inicia el proceso nuevamente.' 
            });
        }

        // 2. Ensure the token is for password reset purpose
        if (decoded.purpose !== 'password_reset') {
            return res.status(400).json({ 
                status: 'error', 
                message: 'Token inválido para esta operación.' 
            });
        }

        // 3. Hash new password
        const passwordHash = await bcrypt.hash(newPassword, SALT_ROUNDS);

        // 4. Update password in DB
        await pool.query(
            'UPDATE users SET password_hash = $1, reset_token = NULL, reset_token_expires = NULL, updated_at = NOW() WHERE id = $2',
            [passwordHash, decoded.id]
        );

        logger.info(`[Password Reset] Password successfully reset for user: ${decoded.id}`);

        res.json({
            status: 'success',
            message: '¡Tu contraseña ha sido actualizada exitosamente! Ya puedes iniciar sesión con tu nueva contraseña.'
        });

    } catch (err) {
        logger.error(`Reset Password Error: ${err.message}`);
        next(err);
    }
};

// POST /api/auth/change-password
// For authenticated users wanting to change their password from the dashboard
export const changePassword = async (req, res, next) => {
    try {
        const userId = req.user.id; // From auth middleware
        const { currentPassword, newPassword } = req.body;

        // 1. Fetch current password hash
        const result = await pool.query('SELECT password_hash FROM users WHERE id = $1', [userId]);
        if (result.rows.length === 0) {
            return res.status(404).json({ status: 'error', message: 'Usuario no encontrado.' });
        }

        // 2. Verify current password
        const isMatch = await bcrypt.compare(currentPassword, result.rows[0].password_hash);
        if (!isMatch) {
            return res.status(401).json({ 
                status: 'error', 
                message: 'La contraseña actual es incorrecta.' 
            });
        }

        // 3. Prevent same password
        const isSame = await bcrypt.compare(newPassword, result.rows[0].password_hash);
        if (isSame) {
            return res.status(400).json({ 
                status: 'error', 
                message: 'La nueva contraseña debe ser diferente a la actual.' 
            });
        }

        // 4. Hash and update
        const passwordHash = await bcrypt.hash(newPassword, SALT_ROUNDS);
        await pool.query(
            'UPDATE users SET password_hash = $1, updated_at = NOW() WHERE id = $2',
            [passwordHash, userId]
        );

        logger.info(`[Password Change] Password changed for user: ${userId}`);

        res.json({
            status: 'success',
            message: 'Tu contraseña ha sido actualizada exitosamente.'
        });

    } catch (err) {
        logger.error(`Change Password Error: ${err.message}`);
        next(err);
    }
};
